# Generated by Django 3.2 on 2021-07-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.DecimalField(decimal_places=1, max_digits=13),
        ),
    ]
