# Generated by Django 3.2 on 2021-07-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qualifier',
            field=models.IntegerField(choices=[('dber', '0'), ('staff', '1')], default=1),
        ),
    ]
