# Generated by Django 3.2 on 2021-07-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_qualifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qualifier',
            field=models.CharField(choices=[('dber', 'dber'), ('staff', 'staff')], default=2, max_length=10),
        ),
    ]
