# Generated by Django 3.2 on 2021-07-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportal', '0004_alter_portal_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='doc',
            field=models.FileField(upload_to='media'),
        ),
    ]
